#ifndef PTEXTUREASSETEDITWIDGET_GLOBAL_H
#define PTEXTUREASSETEDITWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PTEXTUREASSETEDITWIDGET_LIBRARY)
#  define PTEXTUREASSETEDITWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PTEXTUREASSETEDITWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PTEXTUREASSETEDITWIDGET_GLOBAL_H
