#ifndef PIMAGEASSETEDITWIDGET_GLOBAL_H
#define PIMAGEASSETEDITWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PIMAGEASSETEDITWIDGET_LIBRARY)
#  define PIMAGEASSETEDITWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PIMAGEASSETEDITWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PIMAGEASSETEDITWIDGET_GLOBAL_H
