#ifndef PTRANSFORMATIONTOOLBAR_GLOBAL_H
#define PTRANSFORMATIONTOOLBAR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PTRANSFORMATIONTOOLBAR_LIBRARY)
#  define PTRANSFORMATIONTOOLBARSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PTRANSFORMATIONTOOLBARSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PTRANSFORMATIONTOOLBAR_GLOBAL_H
