#ifndef PMATERIALASSETEDITWIDGET_GLOBAL_H
#define PMATERIALASSETEDITWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PMATERIALASSETEDITWIDGET_LIBRARY)
#  define PMATERIALASSETEDITWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PMATERIALASSETEDITWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PMATERIALASSETEDITWIDGET_GLOBAL_H
