#ifndef PTRANSFORMATIONCOMPONENTPROPERTIES_GLOBAL_H
#define PTRANSFORMATIONCOMPONENTPROPERTIES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PTRANSFORMATIONCOMPONENTPROPERTIES_LIBRARY)
#  define PTRANSFORMATIONCOMPONENTPROPERTIESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PTRANSFORMATIONCOMPONENTPROPERTIESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PTRANSFORMATIONCOMPONENTPROPERTIES_GLOBAL_H
