#ifndef PIMAGEASSETHELPER_GLOBAL_H
#define PIMAGEASSETHELPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PIMAGEASSETHELPER_LIBRARY)
#  define PIMAGEASSETHELPERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PIMAGEASSETHELPERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PIMAGEASSETHELPER_GLOBAL_H
